config/routes.rb
Rails.application.routes.draw do
  resources :incidents
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/incident.rb
class Incident < ApplicationRecord
belong_to :user
validates :content, length: {maximum: 250}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :incidents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]

  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.all
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)

    respond_to do |format|
      if @incident.save
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url, notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit(:recordnumberclient, :recordnumber, :group, :module, :dms, :dateexe)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :regnumber, :client)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/incidents/_form.html.erb
<%= form_with(model: incident, local: true) do |form| %>
  <% if incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% incident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recordnumberclient %>
    <%= form.text_field :recordnumberclient, id: :incident_recordnumberclient %>
  </div>

  <div class="field">
    <%= form.label :recordnumber %>
    <%= form.text_field :recordnumber, id: :incident_recordnumber %>
  </div>

  <div class="field">
    <%= form.label :group %>
    <%= form.text_field :group, id: :incident_group %>
  </div>

  <div class="field">
    <%= form.label :module %>
    <%= form.text_field :module, id: :incident_module %>
  </div>

  <div class="field">
    <%= form.label :dms %>
    <%= form.text_field :dms, id: :incident_dms %>
  </div>

  <div class="field">
    <%= form.label :dateexe %>
    <%= form.text_field :dateexe, id: :incident_dateexe %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/incidents/edit.html.erb
<h1>Editing Incident</h1>

<%= render 'form', incident: @incident %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Incidents</h1>

<table>
  <thead>
    <tr>
      <th>Recordnumberclient</th>
      <th>Recordnumber</th>
      <th>Group</th>
      <th>Module</th>
      <th>Dms</th>
      <th>Dateexe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <td><%= incident.recordnumberclient %></td>
        <td><%= incident.recordnumber %></td>
        <td><%= incident.group %></td>
        <td><%= incident.module %></td>
        <td><%= incident.dms %></td>
        <td><%= incident.dateexe %></td>
        <td><%= link_to 'Show', incident %></td>
        <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
        <td><%= link_to 'Destroy', incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incident', new_incident_path %>

app/views/incidents/new.html.erb
<h1>New Incident</h1>

<%= render 'form', incident: @incident %>

<%= link_to 'Back', incidents_path %>

app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recordnumberclient:</strong>
  <%= @incident.recordnumberclient %>
</p>

<p>
  <strong>Recordnumber:</strong>
  <%= @incident.recordnumber %>
</p>

<p>
  <strong>Group:</strong>
  <%= @incident.group %>
</p>

<p>
  <strong>Module:</strong>
  <%= @incident.module %>
</p>

<p>
  <strong>Dms:</strong>
  <%= @incident.dms %>
</p>

<p>
  <strong>Dateexe:</strong>
  <%= @incident.dateexe %>
</p>

<%= link_to 'Edit', edit_incident_path(@incident) %> |
<%= link_to 'Back', incidents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WcNew</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :regnumber %>
    <%= form.text_field :regnumber, id: :user_regnumber %>
  </div>

  <div class="field">
    <%= form.label :client %>
    <%= form.text_field :client, id: :user_client %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Regnumber</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.regnumber %></td>
        <td><%= user.client %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Regnumber:</strong>
  <%= @user.regnumber %>
</p>

<p>
  <strong>Client:</strong>
  <%= @user.client %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>